Repository nextstrain/auspice, pull requests merged in 2024-08, with the labels that each got.

#1804 Only support downloading Auspice JSONs if dataset name can be parsed
  CHANGELOG.md
  src/components/download/downloadButtons.js
  src/components/download/helperFunctions.js
  src/middleware/changeURL.js
Labels: preview on auspice.us

#1827 Limit x-axis by filtered measurements
  CHANGELOG.md
  src/components/measurements/index.js
  src/components/measurements/measurementsD3.js
Labels: preview on nextstrain.org

#1832 Allow YYYY-MM-DD values in a temporal scales
  src/actions/recomputeReduxState.js
  src/util/colorHelpers.js
  src/util/colorScale.js
  src/util/dateHelpers.js
  src/util/tipRadiusHelpers.ts
  test/dates.test.js
Labels: preview on nextstrain.org, preview on auspice.us

#1668 Extend usefulness of tip labels
  CHANGELOG.md
  src/actions/recomputeReduxState.js
  src/components/controls/choose-tip-label.js
  src/components/tree/infoPanels/click.js
  src/components/tree/infoPanels/helpers.js
  src/components/tree/infoPanels/hover.js
  src/components/tree/tree.js
  src/util/treeJsonProcessing.js
Labels: preview on nextstrain.org, preview on auspice.us

#1838 measurements: Revert back to useMemo
  src/components/measurements/index.js
Labels: preview on nextstrain.org

#1836 Scatterplots work with temporal YYYY-MM-DD scales
  src/components/tree/phyloTree/layouts.js
  src/util/scatterplotHelpers.js
Labels: preview on nextstrain.org
